import { chmod } from "node:fs/promises"

const entrypoint = decodeURIComponent(new URL("../src/cli/main.ts", import.meta.url).pathname)
const destination = decodeURIComponent(new URL("../public/boxos-cli.js", import.meta.url).pathname)

export async function buildCli(): Promise<string> {
  const build = await Bun.build({
    entrypoints: [entrypoint],
    target: "node",
    format: "cjs",
    write: false,
  })
  if (!build.success || build.outputs.length != 1) throw new Error("CLI build failed")
  const bundle = (await build.outputs[0]!.text()).replace(/^#![^\n]*\n/, "")
  return `#!/usr/bin/env node\n// Generated by scripts/build_cli.ts. Do not edit.\n${bundle}`
}

if (import.meta.main) {
  await Bun.write(destination, await buildCli())
  await chmod(destination, 0o755)
}
